<?php
/**
 * Routing and page rendering.
 *
 * Each public directory contains a two-line index.php stub (generated by
 * bin/build.php) that calls acad_serve(__DIR__). The directory path is the
 * URL, so clean URLs work on any cPanel host with or without mod_rewrite.
 */
declare(strict_types=1);

/** Entry point for directory stubs. */
function acad_serve(string $dir): never
{
    $rel = trim(str_replace('\\', '/', substr($dir, strlen(ACAD_ROOT))), '/');
    acad_dispatch($rel === '' ? '/' : '/' . $rel . '/');
}

/** Entry point for the front controller / 404 handler. */
function acad_dispatch(string $path): never
{
    $path = acad_normalize_path($path);
    $redirects = acad_redirects();
    if (isset($redirects[$path])) {
        $qs = (string) ($_SERVER['QUERY_STRING'] ?? '');
        acad_redirect($redirects[$path] . ($qs !== '' ? '?' . $qs : ''), 301);
    }

    $page = acad_page($path);
    if ($page === null || !empty($page['virtual'])) {
        acad_not_found();
    }

    $ctx = [];
    if (!empty($page['form'])) {
        acad_session_start();
        if (acad_is_post()) {
            $ctx = acad_handle_form((string) $page['form'], $page['path']);
        }
        $ctx['sent'] = acad_flash_take('sent_' . $page['form']);
    }

    acad_output(acad_render_page($page, $ctx), $page, (int) ($ctx['status'] ?? 200));
}

function acad_not_found(): never
{
    $page = acad_page('/404/');
    acad_output(acad_render_page($page), $page, 404);
}

function acad_output(string $html, array $page, int $status = 200): never
{
    http_response_code($status);
    header('Content-Type: text/html; charset=utf-8');
    acad_send_security_headers(!empty($page['noindex']));
    if (empty($page['form']) && $status === 200) {
        header('Cache-Control: public, max-age=300');
    } else {
        header('Cache-Control: no-store');
    }
    echo $html;
    exit;
}

/** Render a registry page through the shared site chrome. */
function acad_render_page(array $page, array $ctx = []): string
{
    $template = ACAD_ROOT . '/includes/templates/' . basename((string) $page['template']) . '.php';
    if (!is_file($template)) {
        $template = ACAD_ROOT . '/includes/templates/article.php';
    }
    $nav = require ACAD_ROOT . '/data/nav.php';
    ob_start();
    require ACAD_ROOT . '/includes/header.php';
    require $template;
    require ACAD_ROOT . '/includes/footer.php';
    return (string) ob_get_clean();
}

/** Standard closing call-to-action band used by most templates. */
function acad_cta_band(string $title = 'See how Acadlytic fits your institution.', string $text = 'Start with a focused conversation about your workflows, systems and priorities. No generic slideware.'): string
{
    return '<section class="cta-band" aria-labelledby="cta-band-h"><div class="container cta-band-inner"><div>'
        . '<p class="eyebrow on-dark">Next step</p><h2 id="cta-band-h">' . e($title) . '</h2><p>' . e($text) . '</p></div>'
        . '<div class="cta-actions"><a class="btn btn-primary btn-lg" href="/company/request-demo/">Request a Demo ' . icon('arrow') . '</a>'
        . '<a class="btn btn-glass btn-lg" href="/core/contact/">Talk to Our Team</a></div></div></section>';
}

function acad_breadcrumb_html(array $page): string
{
    $trail = acad_breadcrumbs($page);
    $last = count($trail) - 1;
    $items = '';
    foreach ($trail as $i => $crumb) {
        $items .= $i === $last
            ? '<li aria-current="page">' . e($crumb['label']) . '</li>'
            : '<li><a href="' . e($crumb['path']) . '">' . e($crumb['label']) . '</a></li>';
    }
    return '<nav class="breadcrumbs" aria-label="Breadcrumb"><ol>' . $items . '</ol></nav>';
}

/** Card linking to another page (hubs, related content, search results). */
function acad_link_card(array $target, string $class = 'link-card'): string
{
    return '<a class="' . e($class) . '" href="' . e($target['path']) . '"><span class="link-card-icon">' . icon($target['icon']) . '</span>'
        . '<span class="link-card-body"><strong>' . e($target['nav_label'] ?: $target['h1']) . '</strong><span>' . e($target['desc']) . '</span></span>'
        . '<span class="link-card-arrow">' . icon('arrow') . '</span></a>';
}

/** Resolve footer/nav href shorthands (e.g. governance:dpo). */
function acad_nav_href(string $href): string
{
    if (str_starts_with($href, 'governance:')) {
        $g = acad_config('governance.' . substr($href, 11));
        return acad_mailto((string) $g['email'], (string) $g['subject']);
    }
    return $href;
}
