<?php
/**
 * Routing and page rendering.
 *
 * Each public directory contains a two-line index.php stub (generated by
 * bin/build.php) that calls acad_serve(__DIR__). The directory path is the
 * URL, so clean URLs work on any cPanel host with or without mod_rewrite.
 */
declare(strict_types=1);

/** Entry point for directory stubs. */
function acad_serve(string $dir): never
{
    $rel = trim(str_replace('\\', '/', substr($dir, strlen(ACAD_ROOT))), '/');
    acad_dispatch($rel === '' ? '/' : '/' . $rel . '/');
}

/** Entry point for the front controller / 404 handler. */
function acad_dispatch(string $path): never
{
    $path = acad_normalize_path($path);
    $redirects = acad_redirects();
    if (isset($redirects[$path])) {
        $qs = (string) ($_SERVER['QUERY_STRING'] ?? '');
        acad_redirect($redirects[$path] . ($qs !== '' ? '?' . $qs : ''), 301);
    }

    $page = acad_page($path);
    if ($page === null || !empty($page['virtual'])) {
        acad_not_found();
    }

    $ctx = [];
    if (!empty($page['form'])) {
        acad_session_start();
        if (acad_is_post()) {
            $ctx = acad_handle_form((string) $page['form'], $page['path']);
        }
        $ctx['sent'] = acad_flash_take('sent_' . $page['form']);
    }

    acad_output(acad_render_page($page, $ctx), $page, (int) ($ctx['status'] ?? 200));
}

function acad_not_found(): never
{
    $page = acad_page('/404/');
    acad_output(acad_render_page($page), $page, 404);
}

function acad_output(string $html, array $page, int $status = 200): never
{
    http_response_code($status);
    header('Content-Type: text/html; charset=utf-8');
    acad_send_security_headers(!empty($page['noindex']));
    if (empty($page['form']) && $status === 200) {
        header('Cache-Control: public, max-age=300');
    } else {
        header('Cache-Control: no-store');
    }
    echo $html;
    exit;
}

/** Render a registry page through the shared site chrome. */
function acad_render_page(array $page, array $ctx = []): string
{
    $template = ACAD_ROOT . '/includes/templates/' . basename((string) $page['template']) . '.php';
    if (!is_file($template)) {
        $template = ACAD_ROOT . '/includes/templates/article.php';
    }
    $nav = require ACAD_ROOT . '/data/nav.php';
    ob_start();
    require ACAD_ROOT . '/includes/header.php';
    require $template;
    require ACAD_ROOT . '/includes/footer.php';
    return (string) ob_get_clean();
}

/** Standard closing call-to-action band used by most templates. */
function acad_cta_band(string $title = 'See how Acadlytic fits your institution.', string $text = 'Start with a focused conversation about your workflows, systems and priorities. No generic slideware.'): string
{
    return '<section class="cta-band" aria-labelledby="cta-band-h"><div class="container cta-band-inner"><div>'
        . '<p class="eyebrow on-dark">Next step</p><h2 id="cta-band-h">' . e($title) . '</h2><p>' . e($text) . '</p></div>'
        . '<div class="cta-actions"><a class="btn btn-primary btn-lg" href="/company/request-demo/">Request a Demo ' . icon('arrow') . '</a>'
        . '<a class="btn btn-glass btn-lg" href="/core/contact/">Talk to Our Team</a></div></div></section>';
}

function acad_breadcrumb_html(array $page): string
{
    $trail = acad_breadcrumbs($page);
    $last = count($trail) - 1;
    $items = '';
    foreach ($trail as $i => $crumb) {
        $items .= $i === $last
            ? '<li aria-current="page">' . e($crumb['label']) . '</li>'
            : '<li><a href="' . e($crumb['path']) . '">' . e($crumb['label']) . '</a></li>';
    }
    return '<nav class="breadcrumbs" aria-label="Breadcrumb"><ol>' . $items . '</ol></nav>';
}

/** Planned-capability notice for product pages (claims policy: docs/CLAIMS_REGISTER.md). */
function acad_status_notice(array $page): string
{
    if (($page['status'] ?? null) !== 'planned') {
        return '';
    }
    $text = $page['status_note'] ?? ($page['template'] === 'hub'
        ? 'The capabilities in this section are in development and not yet generally available. Pages describe what Acadlytic is designed to do; scope and timing are confirmed with each institution.'
        : 'This page describes what Acadlytic is designed to do. These capabilities are in development and not yet generally available; scope and timing are confirmed with each institution.');
    return '<div class="status-notice" role="note"><span class="status-pill">' . icon('flag', 'icon icon-xs') . 'Planned · In development</span><p>' . e($text) . '</p></div>';
}

/** Visible and machine-readable marker on legal pages awaiting counsel sign-off. */
function acad_legal_marker(array $page): string
{
    if (empty($page['legal_draft'])) {
        return '';
    }
    return "<!-- LEGAL REVIEW REQUIRED — NOT FINAL -->\n"
        . '<div class="legal-marker" role="note"><strong>LEGAL REVIEW REQUIRED — NOT FINAL</strong><span>This draft has not been approved by legal counsel and must not be relied on as Acadlytic’s final policy.</span>'
        . (!empty($page['counsel_items']) ? '<details><summary>For legal counsel to complete</summary><ul><li>' . implode('</li><li>', array_map('e', $page['counsel_items'])) . '</li></ul></details>' : '')
        . '</div>';
}

/** Card linking to another page (hubs, related content, search results). */
function acad_link_card(array $target, string $class = 'link-card'): string
{
    return '<a class="' . e($class) . '" href="' . e($target['path']) . '"><span class="link-card-icon">' . icon($target['icon']) . '</span>'
        . '<span class="link-card-body"><strong>' . e($target['nav_label'] ?: $target['h1']) . (($target['status'] ?? null) === 'planned' ? ' <em class="mini-pill">Planned</em>' : '') . '</strong><span>' . e($target['desc']) . '</span></span>'
        . '<span class="link-card-arrow">' . icon('arrow') . '</span></a>';
}

/**
 * Number-free contact redirects (/go/call/, /go/whatsapp/). The full number
 * lives only in config/contact.php and is sent only in a Location header.
 */
function acad_contact_redirect(string $channel): never
{
    $c = (array) acad_config('contact');
    $target = match ($channel) {
        'call'     => 'tel:' . $c['CONTACT_PHONE'],
        'whatsapp' => 'https://wa.me/' . rawurlencode((string) $c['WHATSAPP_NUMBER']) . '?text=' . rawurlencode((string) $c['WHATSAPP_MESSAGE']),
        default    => '/core/contact/',
    };
    header('Cache-Control: no-store');
    header('X-Robots-Tag: noindex, nofollow');
    header('Referrer-Policy: no-referrer');
    header('Location: ' . $target, true, 302);
    exit;
}

/** Resolve footer/nav href shorthands (e.g. governance:dpo). */
function acad_nav_href(string $href): string
{
    if (str_starts_with($href, 'governance:')) {
        $g = acad_config('governance.' . substr($href, 11));
        return acad_mailto((string) $g['email'], (string) $g['subject']);
    }
    return $href;
}

/** Responsive brand logo (WebP with PNG fallback), shared by the site and auth shells. */
function acad_logo_html(string $class = 'brand-logo', bool $eager = true): string
{
    return '<picture><source type="image/webp" srcset="' . e(asset('/assets/img/logo-acadlytic-56.webp')) . ' 1x, ' . e(asset('/assets/img/logo-acadlytic.webp')) . ' 2x">'
        . '<img class="' . e($class) . '" src="' . e(asset('/assets/img/logo-acadlytic.png')) . '" srcset="' . e(asset('/assets/img/logo-acadlytic-56.png')) . ' 1x, ' . e(asset('/assets/img/logo-acadlytic.png')) . ' 2x"'
        . ' width="207" height="56" alt="Acadlytic, Inc." ' . ($eager ? 'fetchpriority="high"' : 'loading="lazy"') . ' decoding="async"></picture>';
}

/** Brand logo for dark surfaces (white wordmark, full-colour mark). */
function acad_logo_light_html(): string
{
    return '<picture><source type="image/webp" srcset="' . e(asset('/assets/img/logo-acadlytic-light-56.webp')) . ' 1x, ' . e(asset('/assets/img/logo-acadlytic-light.webp')) . ' 2x">'
        . '<img class="brand-logo" src="' . e(asset('/assets/img/logo-acadlytic-light.png')) . '" width="207" height="56" alt="Acadlytic, Inc." loading="lazy" decoding="async"></picture>';
}

/** Shared <head> contents for the site and auth shells (meta, icons, fonts, CSS, JS). */
function acad_head_common(array $page): string
{
    return '<meta charset="utf-8">' . "\n"
        . '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">' . "\n"
        . acad_head_meta($page)
        . '<meta name="theme-color" content="#071A3A">' . "\n"
        . '<meta name="format-detection" content="telephone=no">' . "\n"
        . '<link rel="icon" href="' . e(asset('/favicon.ico')) . '" sizes="48x48">' . "\n"
        . '<link rel="icon" type="image/png" sizes="32x32" href="' . e(asset('/assets/img/favicon-32.png')) . '">' . "\n"
        . '<link rel="icon" type="image/png" sizes="192x192" href="' . e(asset('/assets/img/icon-192.png')) . '">' . "\n"
        . '<link rel="apple-touch-icon" sizes="180x180" href="' . e(asset('/assets/img/apple-touch-icon.png')) . '">' . "\n"
        . '<link rel="manifest" href="' . e(asset('/site.webmanifest')) . '">' . "\n"
        . '<link rel="preload" href="/assets/fonts/manrope-var-latin.woff2" as="font" type="font/woff2" crossorigin>' . "\n"
        . '<link rel="preload" href="/assets/fonts/inter-var-latin.woff2" as="font" type="font/woff2" crossorigin>' . "\n"
        . '<style>' . acad_critical_css() . '</style>' . "\n"
        . '<link rel="stylesheet" href="' . e(asset('/assets/css/main.css')) . '">' . "\n"
        . '<script src="' . e(asset('/assets/js/app.js')) . '" defer></script>' . "\n";
}
